name = "filmzi-movie-and-tv-series-downloader"
compatibility_date = "2024-06-01"
pages_build_output_dir = "public"

[env.production]
# No workers_dev setting for Pages

[env.preview]
# Preview environment settings
